# Generated by Django 5.1.5 on 2025-02-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forensicimage',
            name='hash_value',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
