# Generated by Django 5.1.5 on 2025-02-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Victime', '0002_victime_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidence/')),
                ('evidence_type', models.CharField(choices=[('network', 'Network Evidence (PCAP)'), ('memory', 'Memory Dump'), ('storage', 'Storage Image'), ('log', 'Log File')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Victime',
        ),
    ]
