# Generated by Django 5.1.5 on 2025-02-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Victime', '0003_evidence_delete_victime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Victime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='victimes/')),
                ('type_fichier', models.CharField(blank=True, choices=[('network', 'Network Evidence (PCAP)'), ('memory', 'Memory Dump'), ('storage', 'Storage Image'), ('log', 'Log File')], max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Evidence',
        ),
    ]
