# Generated by Django 5.1.5 on 2025-02-06 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Victime', '0004_victime_delete_evidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='victime',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='victime',
            name='description',
        ),
        migrations.RemoveField(
            model_name='victime',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='victime',
            name='prenom',
        ),
    ]
