# Generated by Django 5.1.5 on 2025-02-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Victime', '0005_remove_victime_date_naissance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='uploads/')),
                ('date_telechargement', models.DateTimeField(auto_now_add=True)),
                ('analyse_completee', models.BooleanField(default=False)),
                ('lien_analyse', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Victime',
        ),
    ]
