# Generated by Django 5.1.5 on 2025-02-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Victime', '0006_trafficanalysis_delete_victime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Victime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='TrafficAnalysis',
        ),
    ]
