# Generated by Django 4.2.19 on 2025-02-16 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Victime', '0009_filehash'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(max_length=64)),
                ('virus_status', models.CharField(choices=[('clean', 'Clean'), ('infected', 'Infected')], default='clean', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_id', models.CharField(blank=True, max_length=255, null=True)),
                ('virus_details', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
