# Generated by Django 4.2.19 on 2025-04-13 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Victime', '0012_alter_fileanalysis_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileanalysis',
            old_name='virus_status',
            new_name='fichier_status',
        ),
    ]
