# Generated by Django 4.2.19 on 2025-04-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Victime', '0013_rename_virus_status_fileanalysis_fichier_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileanalysis',
            name='fichier_status_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
